# Generated by Django 3.1.6 on 2021-02-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
